//to be used with the json file and UVMap Layout png
//generated by ExportVertexNumberedUV.py

JSONArray data;
PImage img;
import processing.svg.*;

//Set offsets for centering stuff. dont need them at all but it looks nice
int xoff=100;
int yoff=-100;
float lerpAmount = 0.75; //how far close to make text to centroid

void setup(){
  size(1024,1024);
  background(255);
  img = loadImage("UVMap.png");
  data = loadJSONArray("UVMap.json");
     
  PGraphics svg = createGraphics(1024, 1024, SVG, "output.svg");
  svg.beginDraw();
  svg.background(255,255,255);
  
 // image(img,100,-100);
  svg.textSize(8);
  svg.fill(255,0,0);
  svg.noStroke();
  
  
  
  
  int curPolyIndex=-1;
  PVector prevPoint = null;
  PVector firstPoint = null;
  PVector offsets = new PVector(xoff,yoff);
  
  svg.noFill();
  svg.beginShape();
  
  for(int i =0;i<data.size();i++){
      JSONArray uvRaw = data.getJSONArray(i);
      int vertex_index = uvRaw.getInt(2);
      
      PVector uv = new PVector(uvRaw.getFloat(0),-uvRaw.getFloat(1));
      PVector textCoord = uv.copy();
      
      JSONArray centroidRaw = uvRaw.getJSONArray(3);
      PVector centroid = new PVector(centroidRaw.getFloat(0),-centroidRaw.getFloat(1));
      
      textCoord.x = lerp(uv.x,centroid.x,lerpAmount);
      textCoord.y = lerp(uv.y,centroid.y,lerpAmount);
      
      textCoord.add(new PVector(0,1));
      textCoord.mult(1024);
      uv.add(new PVector(0,1));
      uv.mult(1024);
      
      uv.add(offsets);
      textCoord.add(offsets);
      
      svg.fill(255,0,0);
      svg.text(vertex_index,textCoord.x,textCoord.y);
      svg.noFill();
      
      if( (prevPoint != null) && curPolyIndex==centroidRaw.getInt(2)){
        svg.stroke(0);
        svg.strokeWeight(0.1);
        svg.vertex(uv.x,uv.y);
      }else if(curPolyIndex!=centroidRaw.getInt(2)){
        if(curPolyIndex!=-1){
          svg.vertex(firstPoint.x,firstPoint.y); 
          svg.endShape(CLOSE);
          svg.beginShape();
        }else svg.vertex(uv.x,uv.y);
       
        curPolyIndex=centroidRaw.getInt(2); 
        firstPoint = uv.copy();
      }
      prevPoint=uv.copy();
  }
  svg.vertex(firstPoint.x,firstPoint.y); 
  svg.endShape(CLOSE);  
  
  svg.dispose();
  svg.endDraw();
  println("Completed");
  
}
